#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

lint_staged_files() {
  echo "⌛ Linting staged files..."
  npx lint-staged --allow-empty
  lintResult=$?

  if [ $lintResult -ne 0 ]; then
    echo "❌ Linting staged files failed"
    exit 1
  fi
}

run_tests() {
  echo "⌛ Running tests..."
  npm test > /dev/null 2>&1
  testResult=$?

  if [ $testResult -ne 0 ]; then
    echo "❌ Running tests failed"
    exit 1
  fi
}


sh ./script/branch-name-validation.sh "$(git branch --show-current)"

lint_staged_files

run_tests

echo "✅ All checks passed. Committing..."

exit 0
